### ISSUE TITLE
PROBLEM: The file name, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by tarred5** [igolaizola/bulkai#57] opened 2023-09-26 19:31 UTC
Hi, I'm getting the following message when I start the system with my prompts to generate the images: The file name, directory name, or volume label syntax is incorrect.

any idea what could be happening? My guess is that it could be a problem with the discord URL, as it continues to generate images on discord, but does not download them to my machine.

Please help me.

**Comment by Auxority** [comment] 2023-09-26 19:38
Duplicate of https://github.com/igolaizola/bulkai/issues/56

**Closed** 2023-09-26 19:48 UTC

**Comment by igolaizola** [comment] 2023-09-26 19:50
Fixed here https://github.com/igolaizola/bulkai/pull/58
